/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.paschal.sat.gui;

import javax.swing.SwingConstants;

/**
 *
 * @author BARBARA.OZUNA
 */
public class ServerGUI extends javax.swing.JFrame {

    /**
     * Creates new form ServerGUI
     */
    public ServerGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        students = new javax.swing.JPanel();
        session1 = new javax.swing.JPanel();
        session2 = new javax.swing.JPanel();
        session3 = new javax.swing.JPanel();
        terminal = new javax.swing.JPanel();
        home = new javax.swing.JPanel();
        img = new javax.swing.JLabel("",SwingConstants.CENTER);
        toolbar = new javax.swing.JMenuBar();
        file = new javax.swing.JMenu();
        view = new javax.swing.JMenu();
        stu = new javax.swing.JMenu();
        stuEntry = new javax.swing.JMenuItem();
        stuList = new javax.swing.JMenuItem();
        s1 = new javax.swing.JMenu();
        ov1 = new javax.swing.JMenuItem();
        st1 = new javax.swing.JMenuItem();
        te1 = new javax.swing.JMenuItem();
        cl1 = new javax.swing.JMenuItem();
        sr1 = new javax.swing.JMenuItem();
        s2 = new javax.swing.JMenu();
        ov2 = new javax.swing.JMenuItem();
        st2 = new javax.swing.JMenuItem();
        te2 = new javax.swing.JMenuItem();
        cl2 = new javax.swing.JMenuItem();
        sr2 = new javax.swing.JMenuItem();
        s3 = new javax.swing.JMenu();
        ov3 = new javax.swing.JMenuItem();
        st3 = new javax.swing.JMenuItem();
        te3 = new javax.swing.JMenuItem();
        cl3 = new javax.swing.JMenuItem();
        sr3 = new javax.swing.JMenuItem();
        term = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        javax.swing.GroupLayout studentsLayout = new javax.swing.GroupLayout(students);
        students.setLayout(studentsLayout);
        studentsLayout.setHorizontalGroup(
            studentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        studentsLayout.setVerticalGroup(
            studentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 579, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout session1Layout = new javax.swing.GroupLayout(session1);
        session1.setLayout(session1Layout);
        session1Layout.setHorizontalGroup(
            session1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );
        session1Layout.setVerticalGroup(
            session1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 557, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout session2Layout = new javax.swing.GroupLayout(session2);
        session2.setLayout(session2Layout);
        session2Layout.setHorizontalGroup(
            session2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
        );
        session2Layout.setVerticalGroup(
            session2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 535, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout session3Layout = new javax.swing.GroupLayout(session3);
        session3.setLayout(session3Layout);
        session3Layout.setHorizontalGroup(
            session3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );
        session3Layout.setVerticalGroup(
            session3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 513, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout terminalLayout = new javax.swing.GroupLayout(terminal);
        terminal.setLayout(terminalLayout);
        terminalLayout.setHorizontalGroup(
            terminalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        terminalLayout.setVerticalGroup(
            terminalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 491, Short.MAX_VALUE)
        );

        home.setEnabled(false);
        home.setPreferredSize(new java.awt.Dimension(747, 513));

        img.setIcon(new javax.swing.ImageIcon(this.getClass().getClassLoader().getResource("images/acorn.png")));

        javax.swing.GroupLayout homeLayout = new javax.swing.GroupLayout(home);
        home.setLayout(homeLayout);
        homeLayout.setHorizontalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLayout.createSequentialGroup()
                .addGap(269, 269, 269)
                .addComponent(img)
                .addContainerGap(478, Short.MAX_VALUE))
        );
        homeLayout.setVerticalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLayout.createSequentialGroup()
                .addComponent(img)
                .addGap(0, 513, Short.MAX_VALUE))
        );

        img.setAlignmentX(400);

        file.setText("File");
        toolbar.add(file);

        view.setText("View");
        toolbar.add(view);

        stu.setText("Students");

        stuEntry.setText("Enter a Student");
        stuEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stuEntryActionPerformed(evt);
            }
        });
        stu.add(stuEntry);

        stuList.setText("Student List");
        stu.add(stuList);

        toolbar.add(stu);

        s1.setText("Session 1");

        ov1.setText("Overview");
        ov1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ov1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ov1ActionPerformed(evt);
            }
        });
        s1.add(ov1);

        st1.setText("Students");
        st1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                st1ActionPerformed(evt);
            }
        });
        s1.add(st1);

        te1.setText("Teachers");
        te1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        te1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        s1.add(te1);

        cl1.setText("Classes");
        s1.add(cl1);

        sr1.setText("Score Reports");
        sr1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sr1ActionPerformed(evt);
            }
        });
        s1.add(sr1);

        toolbar.add(s1);

        s2.setText("Session 2");

        ov2.setText("Overview");
        ov2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ov2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ov2ActionPerformed(evt);
            }
        });
        s2.add(ov2);

        st2.setText("Students");
        st2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                st2ActionPerformed(evt);
            }
        });
        s2.add(st2);

        te2.setText("Classes");
        s2.add(te2);

        cl2.setText("Teachers");
        cl2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cl2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        s2.add(cl2);

        sr2.setText("Score Reports");
        sr2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sr2ActionPerformed(evt);
            }
        });
        s2.add(sr2);

        toolbar.add(s2);

        s3.setText("Session 3");

        ov3.setText("Overview");
        ov3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ov3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ov3ActionPerformed(evt);
            }
        });
        s3.add(ov3);

        st3.setText("Students");
        st3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                st3ActionPerformed(evt);
            }
        });
        s3.add(st3);

        te3.setText("Classes");
        s3.add(te3);

        cl3.setText("Teachers");
        cl3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cl3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        s3.add(cl3);

        sr3.setText("Score Reports");
        sr3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sr3ActionPerformed(evt);
            }
        });
        s3.add(sr3);

        toolbar.add(s3);

        term.setText("Terminal");
        term.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                termActionPerformed(evt);
            }
        });
        toolbar.add(term);

        setJMenuBar(toolbar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(students, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(session1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(session2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(20, 20, 20)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addComponent(session3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(30, 30, 30)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(40, 40, 40)
                    .addComponent(terminal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(40, 40, 40)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(students, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(session1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(session2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(22, 22, 22)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addComponent(session3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(33, 33, 33)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(44, 44, 44)
                    .addComponent(terminal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(44, 44, 44)))
        );

        students.setVisible(false);
        session1.setVisible(false);
        session2.setVisible(false);
        session3.setVisible(false);
        terminal.setVisible(false);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ov1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ov1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ov1ActionPerformed

    private void st1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_st1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_st1ActionPerformed

    private void sr1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sr1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sr1ActionPerformed

    private void ov2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ov2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ov2ActionPerformed

    private void st2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_st2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_st2ActionPerformed

    private void sr2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sr2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sr2ActionPerformed

    private void ov3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ov3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ov3ActionPerformed

    private void st3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_st3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_st3ActionPerformed

    private void sr3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sr3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sr3ActionPerformed

    private void termActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_termActionPerformed
        terminal.setVisible(true);
    }//GEN-LAST:event_termActionPerformed

    private void stuEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stuEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stuEntryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServerGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cl1;
    private javax.swing.JMenuItem cl2;
    private javax.swing.JMenuItem cl3;
    private javax.swing.JMenu file;
    private javax.swing.JPanel home;
    private javax.swing.JLabel img;
    private javax.swing.JMenuItem ov1;
    private javax.swing.JMenuItem ov2;
    private javax.swing.JMenuItem ov3;
    private javax.swing.JMenu s1;
    private javax.swing.JMenu s2;
    private javax.swing.JMenu s3;
    private javax.swing.JPanel session1;
    private javax.swing.JPanel session2;
    private javax.swing.JPanel session3;
    private javax.swing.JMenuItem sr1;
    private javax.swing.JMenuItem sr2;
    private javax.swing.JMenuItem sr3;
    private javax.swing.JMenuItem st1;
    private javax.swing.JMenuItem st2;
    private javax.swing.JMenuItem st3;
    private javax.swing.JMenu stu;
    private javax.swing.JMenuItem stuEntry;
    private javax.swing.JMenuItem stuList;
    private javax.swing.JPanel students;
    private javax.swing.JMenuItem te1;
    private javax.swing.JMenuItem te2;
    private javax.swing.JMenuItem te3;
    private javax.swing.JMenu term;
    private javax.swing.JPanel terminal;
    private javax.swing.JMenuBar toolbar;
    private javax.swing.JMenu view;
    // End of variables declaration//GEN-END:variables
}
